FROM node:16-alpine

WORKDIR /app

# Copia apenas os arquivos de dependências para aproveitar o cache
COPY package.json package-lock.json* ./

RUN npm install

# Copia todo o código fonte para o container
COPY . .

EXPOSE 3000

CMD ["npm", "start"]