# Stage 1: Build do projeto React com TypeScript
FROM node:16-alpine as build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Servir os arquivos com Nginx
FROM nginx:alpine
# Copia o build do React para o diretório padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

# Inicia o Nginx no primeiro plano
CMD ["nginx", "-g", "daemon off;"]